#! /bin/bash

echo "Deploying Lambda λ"
tmux new-session -d -s lambda "cd /home/omarsaldanna/Lambda && python3 lambda/app.py"
tmux new-session -d -s discordo "cd /home/omarsaldanna/Lambda && python3 discordo/app.py"
